    queryaddress = '/home/hlabbunri/Desktop/chenxi wang/wrs-wcx/wcx/Assemble task/data/image/rotation_5.pgm';
    tempaddress = '/home/hlabbunri/Desktop/chenxi wang/wrs-wcx/wcx/Assemble task/data/image/template_edge.pgm';
    size_min_x = 209;
    size_min_y = 25;
    size_max_x = 536;
    size_max_y = 303;
    times = 5;
% [part_num, cost] = chamfermatching_nopic_forpython(queryaddress, tempaddress, size_min_x, size_min_y, size_max_x, size_max_y,times);
cost = chamfermatching_no_pos_no_num(queryaddress, tempaddress);